apiVersion: v1
kind: ServiceAccount
metadata:
  name: storageclass-patcher
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: storageclass-patcher
rules:
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: storageclass-patcher
subjects:
  - kind: ServiceAccount
    name: storageclass-patcher
    namespace: default
roleRef:
  kind: ClusterRole
  name: storageclass-patcher
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: set-default-storageclass
  namespace: default
spec:
  ttlSecondsAfterFinished: 10
  template:
    spec:
      serviceAccountName: storageclass-patcher
      restartPolicy: Never
      containers:
        - name: kubectl
          image: bitnami/kubectl:latest
          command:
            - kubectl
            - annotate
            - storageclass
            - gp2
            - storageclass.kubernetes.io/is-default-class=true
            - --overwrite
