apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-storageclass.yaml
  - 01-service-account.yaml
  - 02-service-a.yaml
  - 03-service-b.yaml
  - 04-secret-provider.yaml
  - 05-sync-secret-job.yaml
  - 08-ingress.yaml
  - 09-grafana-dashboards.yaml
